=begin
#Avalara Shipping Verification only

#API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

module AvalaraSDK
  VERSION = '2.3.0'
end
