=begin
#Avalara Shipping Verification for Beverage Alcohol

#API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 

The version of the OpenAPI document: 2.1.0-beta

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AvalaraSdk::AgeVerifyFailureCode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AvalaraSdk::AgeVerification::AgeVerifyFailureCode do
  let(:instance) { AvalaraSdk::AgeVerification::AgeVerifyFailureCode.new }

  describe 'test an instance of AgeVerifyFailureCode' do
    it 'should create an instance of AgeVerifyFailureCode' do
      expect(instance).to be_instance_of(AvalaraSdk::AgeVerification::AgeVerifyFailureCode)
    end
  end
end
