=begin
#Avalara Shipping Verification for Beverage Alcohol

#API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 

The version of the OpenAPI document: 2.1.0-beta

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AvalaraSdk::ErrorDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AvalaraSdk::Shipping::ErrorDetails do
  let(:instance) { AvalaraSdk::Shipping::ErrorDetails.new }

  describe 'test an instance of ErrorDetails' do
    it 'should create an instance of ErrorDetails' do
      expect(instance).to be_instance_of(AvalaraSdk::Shipping::ErrorDetails)
    end
  end
  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
