=begin
#Avalara Shipping Verification only

#API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

# Common files
require 'Avalara.SDK/api_client'
require 'Avalara.SDK/api_error'
require 'Avalara.SDK/version'
require 'Avalara.SDK/configuration'

# Models
require 'Avalara.SDK/models/age_verify_failure_code'
require 'Avalara.SDK/models/age_verify_request'
require 'Avalara.SDK/models/age_verify_request_address'
require 'Avalara.SDK/models/age_verify_result'
require 'Avalara.SDK/models/error_details'
require 'Avalara.SDK/models/error_details_error'
require 'Avalara.SDK/models/error_details_error_details'
require 'Avalara.SDK/models/shipping_verify_result'
require 'Avalara.SDK/models/shipping_verify_result_lines'

# APIs
require 'Avalara.SDK/api/age_verification_api'
require 'Avalara.SDK/api/shipping_verification_api'

module AvalaraSDK
  class << self
    # Customize default settings for the SDK using block.
    #   AvalaraSDK.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
