name: Ruby Test

on: push

jobs:
  build:
    name: Execute Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build & test
      run: |
        gem build *.gemspec
        bundle config set --local path 'vendor/bundle'
        bundle install
        bundle exec rspec
